version: '3.8'
services:
  db:
    container_name: database
    image: mysql
    environment:
      MYSQL_DATABASE: tasksdb
      MYSQL_ROOT_PASSWORD: DevOps@123
    ports:
      - "3306:3306"
    volumes:
      - mysql-database:/var/lib/mysql
    networks:
      - devops-task-api
    restart: always
    healthcheck:
      test: ["CMD","ping","-h","localhost","-uroot","-pDevOps@123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s