version: '3.8'
services:
  db:
    container_name: database
    image: mysql
    environment:
      MYSQL_DATABASE: tasksdb
      MYSQL_ROOT_PASSWORD: DevOps@123
    ports:
      - "3306:3306"
    volumes:
      - mysql-database:/var/lib/mysql
    networks:
      - devops-task-api
    restart: always
         